### ISSUE TITLE
vcpkg cannot install mmio

### ISSUE THREAD

**Issue by BB-84C** [Ryan-rsm-McKenzie/mmio#2]
Hi, thanks for the huge contribution to the Fallout 4 community! I'm building an F4SE program that is cloned from github. The building failed and prompted: 

> 

> CMake Error at F:/Development/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
>   Could not find a package configuration file provided by "mmio" with any of
>   the following names:
> 
>     mmioConfig.cmake
>     mmio-config.cmake
> 
>   Add the installation prefix of "mmio" to CMAKE_PREFIX_PATH or set
>   "mmio_DIR" to a directory containing one of the above files.  If "mmio"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   extern/CommonLibF4/AddressLibDecoder/CMakeLists.txt:12 (find_package)

Then I cd to vcpkg path and entered: 

> vcpkg install mmio

Then it returned:

> CMake Error at scripts/ports.cmake:113 (message):
>   Port is missing portfile: F:/Development/vcpkg/ports/mmio/portfile.cmake
> 
> 
> error: building mmio:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
> Then check for known issues at:
>     https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+mmio
> You can submit a new issue at:
>     https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[mmio]+Build+error
> Include '[mmio] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
>     vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
>     vcpkg-scripts version: 0257395b0 2022-07-26 (1 year, 5 months ago)
> 
> You can also use the prefilled template from F:\Development\vcpkg\installed\vcpkg\issue_body.md.

Where did I do wrong? I'm pretty new to xSE & C++ development, any help will be appreciated! Thanks!

**Comment by Ryan-rsm-McKenzie** [comment]
It should be `rsm-mmio` instead of `mmio`

**Comment by BB-84C** [comment]
Thank you so much. I can install it right now.
