### ISSUE TITLE
CreateFileW long paths

### ISSUE THREAD

**Issue by ARoese** [Ryan-rsm-McKenzie/mmio#3]
Hello, I found this repo while looking for sources of a known issue in [Skyrim Open Animation Replacer](https://github.com/ersh1/OpenAnimationReplacer) where long paths cause issues. It uses this repo for certain file operations.

I believe the issue stems from this call to CreateFileW: 
https://github.com/Ryan-rsm-McKenzie/mmio/blob/b13cc7e0b4290b9379b2376314f86f304aaf8c34/src/mmio/mmio.cpp#L471C3-L472C11

According to [win32 documentation](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew), CreateFileW allows paths up to 32,767 wide characters only if the path is prefixed with `\\?\`. Otherwise, paths are still limited to the old max of 260 characters which is fairly restrictive.

If you prefer to leave the decision of 260 vs 32,767 character paths up to library users, please make this explicit in the documentation or README.

**Comment by Ryan-rsm-McKenzie** [comment]
This library passes the contents of `std::filesystem::path::c_str` directly to `CreateFileW`. I don't ever touch the contents of the path. If you need to support long paths, then you should construct `std::filesystem::path` using the long path form.
